name: Angular CI/CD

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: app-roman-04 # Remplacez par le nom de votre application Azures Web App
  AZURE_WEBAPP_PACKAGE_PATH: './dist'   # Répertoire de build de l'applicastion Angular
  NODE_VERSION: '20.x'                # Version de Node.js à utiliser

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: Azure Login
        run: az login

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies and build Angular app
        run: |
          npm install
          npm run build --prod
        working-directory: .  # Assurez-vous de spécifier le bon répertoire si nécessaire

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Azure Logout
        run: az logout
